classes:
- service.git.client
- system.linux.system.single
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.reclass.storage.salt
- system.salt.minion.pki.authority
- system.salt.minion.pki.certificate
- system.sphinx.server.doc.reclass
- system.keystone.client.single
- system.keystone.client.service.nova21
- system.mysql.client.single
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_compute_single
- system.reclass.storage.system.openstack_dashboard_single
- system.reclass.storage.system.stacklight_server_cluster
- cluster.mk22_lab_advanced
parameters:
  _param:
    reclass_data_repository: "git@github.com:Mirantis/mk-lab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: 192.168.10.100
    single_address: 172.16.10.100
    salt_master_host: 127.0.0.1
    salt_master_base_environment: prd
    salt_minion_ca_host: ${linux:network:fqdn}
  linux:
    network:
      interface:
        ens4:
          enabled: true
          type: eth
          proto: dhcp
  reclass:
    storage:
      node:
        openstack_control_node01:
          classes:
          - service.galera.master.cluster
          params:
            mysql_cluster_role: master
        openstack_control_node02:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
        openstack_control_node03:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
  salt:
    master:
      environment:
        dev:
          formula:
            cinder:
              revision: stacklight
            collectd:
              revision: stacklight
            elasticsearch:
              revision: stacklight
            galera:
              revision: stacklight
            glance:
              revision: stacklight
            glusterfs:
              revision: stacklight
            grafana:
              revision: stacklight
              state:
                grafana3_datasource.py:
                  enabled: true
                grafana3_dashboard.py:
                  enabled: true
            haproxy:
              revision: stacklight
            heat:
              revision: stacklight
            heka:
              revision: stacklight
              module:
                heka_alarming.py:
                  enabled: true
            influxdb:
              revision: stacklight
            keepalived:
              revision: stacklight
            keystone:
              revision: stacklight
            kibana:
              revision: stacklight
              state:
                kibana_object.py:
                  enabled: true
            linux:
              revision: stacklight
              module:
                linux_netlink.py:
                  enabled: true
            memcached:
              revision: stacklight
            nagios:
              module:
                nagios_alarming.py:
                  enabled: true
            neutron:
              revision: stacklight
            nginx:
              revision: stacklight
            nova:
              revision: stacklight
            ntp:
              revision: stacklight
            opencontrail:
              revision: stacklight
            rabbitmq:
              revision: stacklight
            swift:
              revision: stacklight
