classes:
- service.grafana.server.single
parameters:
  _param:
    grafana_port: 3000
    grafana_user: admin
    grafana_password: admin
  linux:
    system:
      repo:
        grafana:
          enabled: true
          source: 'deb https://packagecloud.io/grafana/stable/debian/ jessie main'
          key_url: 'https://packagecloud.io/gpg.key'
  grafana:
    server:
      enabled: true
      bind:
        address: ${_param:single_address}
        port: ${_param:grafana_port}
      database:
        engine: mysql
        host: ${_param:openstack_database_address}
        port: 3306
        name: grafana
        user: grafana
        password: ${_param:mysql_grafana_password}
      auth:
        engine: basic
      admin:
        user: ${_param:grafana_user}
        password: ${_param:grafana_password}
      dashboards:
        enabled: false
        path: /var/lib/grafana/dashboards
