parameters:
  _param:
    jenkins_deploy_lab_mk_jobs: []
  jenkins:
    client:
      job_template:
        deploy_heat_template:
          name: deploy-{{stack_type}}-{{lab}}
          jobs: ${_param:jenkins_deploy_lab_mk_jobs}
          template:
            type: workflow-scm
            discard:
              build:
                keep_num: 20
            concurrent: true
            display_name: "Deploy - {{lab}} {{stack_type}} lab"
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
              credentials: "gerrit"
              script: lab-pipeline.groovy
            trigger:
              timer:
                spec: "{{timer}}"
            param:
              # deployments and test settings
              STACK_TYPE:
                type: string
                default: "{{stack_type}}"
              INSTALL:
                type: string
                default: "{{install}}"
              TEST:
                type: string
                default: "{{test}}"

              # heat
              HEAT_TEMPLATE_URL:
                type: string
                default: "${_param:jenkins_gerrit_url}/mk/heat-templates"
              HEAT_TEMPLATE_CREDENTIALS:
                type: string
                default: "gerrit"
              HEAT_TEMPLATE_BRANCH:
                type: string
                default: "master"
              HEAT_STACK_NAME:
                type: string
                description: Heat stack name. Will be generated if missing.
              HEAT_STACK_TEMPLATE:
                type: string
                default: "{{lab}}"
              HEAT_STACK_ENVIRONMENT:
                type: string
                default: "tcpisek"
              HEAT_STACK_ZONE:
                type: string
                default: "mirantis-zone-qa"
              HEAT_STACK_PUBLIC_NET:
                type: string
                default: "mirantis-private"
              HEAT_STACK_DELETE:
                type: boolean
                default: 'true'
                description: "Don't enable it if you need to use the lab after"
              HEAT_STACK_REUSE:
                type: boolean
                default: 'false'

              # salt master
              SALT_MASTER_CREDENTIALS:
                type: string
                default: "salt-qa-credentials"
              SALT_MASTER_URL:
                type: string
                default: ""

              # openstack api
              OPENSTACK_API_URL:
                type: string
                default: "https://vpc.tcpisek.cz:5000/v2.0"
              OPENSTACK_API_CREDENTIALS:
                type: string
                default: "openstack-qa-credentials"
              OPENSTACK_API_PROJECT:
                type: string
                default: "mirantis_mk20_qa"
              OPENSTACK_API_CLIENT:
                type: string
                default: "liberty"
              OPENSTACK_API_VERSION:
                type: string
                default: "2"

              # k8s setttings
              K8S_API_SERVER:
                type: string
                default: "http://127.0.0.1:8080"
              K8S_CONFORMANCE_IMAGE:
                type: string
                default: "docker-dev-virtual.docker.mirantis.net/mirantis/kubernetes/k8s-conformance:v1.5.1-3_1482332392819"

              # Tempest settings
              TEMPEST_IMAGE_LINK:
                type: string
                default: "sandbox-docker-prod-local.docker.mirantis.net/mirantis/rally_tempest:0.1"

              ASK_ON_ERROR:
                type: boolean
                default: 'false'

