classes:
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.git
- system.salt.minion.pki.authority
- system.reclass.storage.salt
- system.reclass.storage.system.opencontrail_analytics_cluster
- system.reclass.storage.system.opencontrail_control_cluster
- system.reclass.storage.system.opencontrail_gateway_single
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_compute_multi
- system.reclass.storage.system.openstack_proxy_single
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- system.reclass.storage.system.stacklight_log_cluster
- system.reclass.storage.system.stacklight_monitor_cluster
- system.reclass.storage.system.stacklight_telemetry_cluster
- cluster.mk22_full_scale
parameters:
  _param:
    salt_master_base_environment: dev
    reclass_data_repository: "git@github.com:Mirantis/mk-lab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: 192.168.10.100
    single_address: ${_param:fuel_config_address}
    salt_master_host: 127.0.0.1
    salt_minion_ca_host: ${linux:network:fqdn}
  linux:
    network:
      interface:
        ens4: ${_param:linux_static_interface}
  reclass:
    storage:
      node:
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
