classes:
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.pki.authority
- system.reclass.storage.salt
- system.reclass.storage.system.opencontrail_control_cluster
- system.reclass.storage.system.opencontrail_gateway_single
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_compute_multi
- system.reclass.storage.system.openstack_proxy_single
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- cluster.mk22-qa-bare-metal-01
parameters:
  _param:
    salt_master_environment_repository: "https://github.com/tcpcloud"
    salt_master_environment_revision: master
    salt_master_base_environment: dev
    reclass_data_repository: "git@github.com:TimurNurlygayanov/mk-lab-salt-model.git"
    reclass_data_revision: dash
    reclass_config_master: ${_param:fuel_config_address}
    salt_master_host: ${_param:fuel_config_address}
    salt_minion_ca_host: ${linux:network:fqdn}
  linux:
    network:
      interface:
        eth0: ${_param:linux_static_interface}
  reclass:
    storage:
      node:
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
