classes:
- service.git.client
- system.linux.system.single
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.git
- system.reclass.storage.salt
- system.salt.minion.pki.authority
- system.salt.minion.pki.certificate
- system.sphinx.server.doc.reclass
- system.keystone.client.single
- system.mysql.client.single
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_compute_single
- system.reclass.storage.system.openstack_dashboard_single
- system.reclass.storage.system.monitoring_service_single
- cluster.mk22_lab_basic_ceilometer
parameters:
  _param:
    salt_master_environment_repository: "https://github.com/tcpcloud"
    salt_master_environment_revision: master
    salt_master_base_environment: dev
    reclass_data_repository: "git@github.com:ityaptin/mk-lab-salt-model.git"
    reclass_data_revision: dash
    reclass_config_master: 192.168.10.100
    single_address: 172.16.10.100
    salt_master_host: 127.0.0.1
    salt_minion_ca_host: ${linux:network:fqdn}
  linux:
    network:
      interface:
        ens4:
          enabled: true
          type: eth
          proto: dhcp
  reclass:
    storage:
      node:
        openstack_control_node01:
          classes:
          - service.galera.master.cluster
          params:
            mysql_cluster_role: master
        openstack_control_node02:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
        openstack_control_node03:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
  salt:
    master:
      environment:
        dev:
          formula:
            cinder:
              revision: stacklight
            collectd:
              revision: stacklight
            galera:
              revision: stacklight
            glance:
              revision: stacklight
            haproxy:
              revision: stacklight
            heat:
              revision: stacklight
            heka:
              revision: stacklight
            keystone:
              revision: stacklight
            linux:
              revision: stacklight
            memcached:
              revision: stacklight
            neutron:
              revision: stacklight
            nova:
              revision: stacklight
            ntp:
              revision: stacklight
            rabbitmq:
              revision: stacklight
