classes:
- service.git.client
- system.linux.system.single
- system.linux.system.repo.mcp.salt
- system.openssh.client.lab
- system.salt.master.api
- system.salt.master.pkg
- system.reclass.storage.salt
- system.salt.minion.ca.salt_master
- system.salt.minion.cert.proxy
- system.sphinx.server.doc.reclass
- system.keystone.client.single
- system.keystone.client.service.aodh
- system.keystone.client.service.ceilometer
- system.keystone.client.service.nova21
- system.keystone.client.service.glare
- system.keystone.client.service.cinder3
- system.keystone.client.service.designate
- system.mysql.client.single
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.opencontrail_control_cluster
- system.reclass.storage.system.openstack_compute_multi
- system.reclass.storage.system.openstack_dashboard_single
- system.reclass.storage.system.openstack_proxy_single
- cluster.os_ha_contrail.openstack.proxy
- cluster.os_ha_contrail
parameters:
  _param:
    reclass_data_repository: "https://gerrit.mcp.mirantis.net/salt-models/mcp-virtual-lab"
    reclass_data_revision: master
    reclass_config_master: 192.168.10.100
    single_address: 172.16.10.100
    salt_master_host: 127.0.0.1
    salt_master_base_environment: prd
    salt_minion_ca_host: ${linux:network:fqdn}
    salt_api_password_hash: "$6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1"
  linux:
    network:
      interface:
        ens4:
          enabled: true
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
  nginx:
    server:
      site:
        nginx_proxy_openstack_web:
          proxy:
            host: prx
        nginx_proxy_openstack_api_heat_cfn:
          enabled: false
  reclass:
    storage:
      node:
        openstack_control_node01:
          classes:
          - service.galera.master.cluster
          params:
            mysql_cluster_role: master
            linux_system_codename: xenial
        openstack_control_node02:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
            linux_system_codename: xenial
        openstack_control_node03:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
            linux_system_codename: xenial
        openstack_proxy_node01:
          classes:
          - cluster.os_ha_contrail.openstack.proxy
          params:
            linux_system_codename: xenial
